Multi study export
BioImage-Archive/bia-integrator pull request #152
Opened 2024-08-19 11:03 UTC by sherwoodf

- Make ingest CLI accept a list of accession IDs and process them all
- Moved some log statements from info to debug, and added -v option to print debug logs
- Used rich to create colour code CLI output and make a summary table

Other changes included:

- Small model update, making features analysed optional

![Screenshot 2024-08-19 at 12 00 07](https://github.com/user-attachments/assets/9cdc3554-af35-4eb9-b4b4-f52ff7b3ebf8)

2024-08-19 13:32 UTC, sherwoodf commented on bia-export/test/output_data/bia_export.json
>  {
The git diff for this is confusing. All that has happened is instead of:
```
{
    "uuid": "a2fdbd58-ee11-4cd9-bc6a-f3d3da7fff71",
   "accession_id": "S-BIADTEST",
    ...
}
```
the file is now:
```
{
    "S-BIADTEST": {
        "uuid": "a2fdbd58-ee11-4cd9-bc6a-f3d3da7fff71",
        "accession_id": "S-BIADTEST",
        ...
    }
}
```

2024-08-19 16:07 UTC, sherwoodf commented on bia-ingest-shared-models/bia_ingest_sm/cli_logging.py
> +    SpecimenImagingPreparationProtocol_ValidationErrorCount: int = Field(default=0)
Note that this field won't get filled in until https://github.com/BioImage-Archive/bia-integrator/pull/139 is merged because there's a typo in the name of the class (Prepartion vs Preparation)

2024-08-19 20:09 UTC, kbab commented on bia-ingest-shared-models/bia_ingest_sm/biostudies.py
> +logger = logging.getLogger('biaingest')
I am guessing this change is to consolidate the logs during ingestion. However, what of the scenario where this module is used by something other than biaingest?

2024-08-19 20:22 UTC, kbab commented on bia-ingest-shared-models/bia_ingest_sm/cli_logging.py
> +def tabulate_errors(dict_of_results: dict[ObjectValidationResult]) -> Table:
should type hint for `dict_of_results` be `dict[str, ObjectValidationResult]` ?

2024-08-19 20:39 UTC, kbab commented on bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
> +            log_failed_model_creation(bia_data_model.Study, result_summary)
Should this be `bia_data_model.ExperimentalImagingDataset`?

2024-08-19 20:43 UTC, kbab commented on bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
> +    RESULT_SUMMARY: dict
Is there a special reason why `RESULT_SUMMARY` is upper case here?

2024-08-19 20:54 UTC, kbab commented on bia-ingest-shared-models/bia_ingest_sm/conversion/study.py
> +            log_failed_model_creation(semantic_models.Contributor, result_summary)
`Contributor` -> `Afflilation`

2024-08-19 20:55 UTC, kbab commented on bia-ingest-shared-models/bia_ingest_sm/conversion/study.py
> +            log_failed_model_creation(semantic_models.Contributor, result_summary)
`Contributor` -> `Publication`

2024-08-19 21:33 UTC, kbab requested changes
Looks really good! Some minor issues maybe to do with copy/paste - see comments

2024-08-20 08:28 UTC, sherwoodf commented on bia-ingest-shared-models/bia_ingest_sm/biostudies.py
> +logger = logging.getLogger('biaingest')
Not sure what you mean by consolidate logs, but i changed this to allow the cli to control the verbosity of all the logs - otherwise i think you would need to pass the verbosity level to each component when logging.

I think this would still log if it were imported by something that also used getLogger biaingest.

I didn't look it up before changing it, but https://stackoverflow.com/questions/50714316/how-to-use-logging-getlogger-name-in-multiple-modules might be a nicer solution that covers both situations?

2024-08-20 08:28 UTC, sherwoodf commented on bia-ingest-shared-models/bia_ingest_sm/cli_logging.py
> +def tabulate_errors(dict_of_results: dict[ObjectValidationResult]) -> Table:
Yes, definitely.

2024-08-20 08:29 UTC, sherwoodf commented on bia-ingest-shared-models/bia_ingest_sm/cli_logging.py
> +        validation_result: ObjectValidationResult = dict_of_results[accession_id_key]
Only for type hinting, but i think that that might be fixed if i fix the type hint you commented above.

2024-08-20 08:30 UTC, sherwoodf commented on bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
> +            log_failed_model_creation(bia_data_model.Study, result_summary)
Yes

2024-08-20 08:31 UTC, sherwoodf commented on bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
> +    RESULT_SUMMARY: dict
This is a mistake. I originally tried making it a global variable, and then when it came to testing it was so hard to get the tests working correctly i ended up just wiring the variable through all the methods

2024-08-20 11:01 UTC, kbab approved these changes
LGTM - not sure if you intentionally left RESULT_SUMMARY as ucase in studies.get_grant

2024-08-20 15:29 UTC, merged