Image conversion using api
BioImage-Archive/bia-integrator pull request #204
Opened 2024-09-18 13:45 UTC by kbab

Convert images to zarr format and create STATIC AND INTERACTIVE_DISPLAY images
Upload to S3
Update image_representation models in API (or on disk)

2024-09-19 09:38 UTC, liviuba commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
I would really not call this (any any related things) a serialiser

2024-09-19 09:41 UTC, liviuba commented on bia-ingest/bia_ingest/serialiser.py
> +class MongodbSerialiser(Serialiser):
Is mongodb the thing this directly interacts with?

2024-09-19 09:57 UTC, liviuba requested changes
Main change request is around some misleading naming, not the approach.

A minor thing to consider but happy to merge without is that generic/untyped gets like in the Serialiser* classes make IDE attribute completion support impossible and cancel the benefit of the api client explicitly being typed. Might slow down future work by having to constantly refer to the model docs / memorise them

2024-09-19 10:01 UTC, kbab commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
Happy to change the name - what do you suggest?

2024-09-19 10:05 UTC, kbab commented
> A minor thing to consider but happy to merge without is that generic/untyped gets like in the Serialiser* classes make IDE attribute completion support impossible and cancel the benefit of the api client explicitly being typed. Might slow down future work by having to constantly refer to the model docs / memorise them

Is there a way to work around this? The class was created in an attempt to allow using either the API or writing to disk . If we are really sure we do not want to have writing to disk functionality, I can use the changes you implemented in the `persist` function instead

2024-09-19 10:06 UTC, liviuba commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
I'm not sure, what makes this a serialiser as opposed to something else?

2024-09-19 10:12 UTC, kbab commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
I used the name 'serialiser' because it takes an object and stores it as a json document either on disk or in the database (I assume this is serialisation?) and retrieves from json doc into object (deserialisation?) ...

2024-09-19 10:25 UTC, liviuba commented
> > A minor thing to consider but happy to merge without is that generic/untyped gets like in the Serialiser* classes make IDE attribute completion support impossible and cancel the benefit of the api client explicitly being typed. Might slow down future work by having to constantly refer to the model docs / memorise them
> 
> Is there a way to work around this? The class was created in an attempt to allow using either the API or writing to disk . If we are really sure we do not want to have writing to disk functionality, I can use the changes you implemented in the `persist` function instead

I don't think the changes I made added / were intended to add typing

2024-09-19 10:26 UTC, liviuba commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
This seems to be doing more than serialisation, and it's not serialisation format that it abstracts

ex https://en.wikipedia.org/wiki/Serialization https://en.wikipedia.org/wiki/Comparison_of_data-serialization_formats

2024-09-19 10:29 UTC, kbab commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
Just looked up definition of serialisation. Is your point that it is the process of conversion to the form that can be stored as opposed to implementing the actual storage/retrieval?

2024-09-19 10:30 UTC, kbab commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
> This seems to be doing more than serialisation, and it's not serialisation format that it abstracts
> 
> ex https://en.wikipedia.org/wiki/Serialization https://en.wikipedia.org/wiki/Comparison_of_data-serialization_formats

Yes it is!

2024-09-19 10:33 UTC, kbab commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
How about `PersistenceStrategy` -> `DiskPersistence` and `MongodbPersistence`?

2024-09-19 10:35 UTC, liviuba commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
Seems closer aligned with what it does to me. Is Mongo a direct dependency of that part of the code?

2024-09-19 10:39 UTC, kbab commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
No, I guess `ApiPersistence` is more appropriate?

2024-09-19 10:44 UTC, liviuba commented on bia-ingest/bia_ingest/serialiser.py
> +from uuid import UUID
yes IMO

https://en.wikipedia.org/wiki/Law_of_Demeter

2024-09-23 14:57 UTC, sherwoodf approved these changes

2024-09-23 15:03 UTC, merged