Make ingest use persistence strategy (API/disk)
BioImage-Archive/bia-integrator pull request #214
Opened 2024-10-02 15:48 UTC by kbab

Address clickup ticket https://app.clickup.com/t/8695e2y7p . The ingest command can now either persist using the API or read/write artefacts to disk. The readme has been updated.

2024-10-03 09:34 UTC, sherwoodf commented
Should the default be on disk? I'm a bit worried about the default making changing to the API...

2024-10-03 09:40 UTC, sherwoodf commented
Minor comment, but i think it would be better if the 'written' log lines were debug level - these can always be viewed with a -v, and would reduce the quantity of output when dealing with long file lists.
![image](https://github.com/user-attachments/assets/44d8f9de-5fe6-474c-8049-b341ad33b78e)

2024-10-03 10:17 UTC, liviuba commented on bia-converter-light/README.md
Just wondering, is there an easy way to create the dependencies for one run of `convert-image`? As in, I'd like to run it once on my local on a fresh db, how can I get a (dummy) image representation to run it on?

2024-10-03 10:20 UTC, liviuba commented on bia-converter-light/README.md
oh, or maybe some ingest commands on real data but known to be small / useable as a test?

2024-10-03 10:25 UTC, liviuba commented on bia-ingest/bia_ingest/conversion/image_annotation_dataset.py
> +    persister: Optional[PersistenceStrategy | None] = None,
I think Optional[Thing] is defined as `Thing | None`, so the one in brackets is redundant (here and in a few other places)

2024-10-03 10:32 UTC, liviuba commented on bia-converter-light/README.md
nvm just realised some small changes for bia-converter-light got bundled in but the PR is mainly for ingest (dummy data to run on local would still be useful IMO, but out of scope)

2024-10-03 10:40 UTC, kbab commented
> Should the default be on disk? I'm a bit worried about the default making changing to production data...

I am happy to change this. My impression was that the most common use would be for the API, but I guess users may want to explore things locally before running against the API. @liviuba do you have a preference for the default?

2024-10-03 10:47 UTC, liviuba commented
> > Should the default be on disk? I'm a bit worried about the default making changing to production data...
> 
> I am happy to change this. My impression was that the most common use would be for the API, but I guess users may want to explore things locally before running against the API. @liviuba do you have a preference for the default?

No strong preference aside from really wanting 'Undo' functionality in the api :) @sherwoodf what's the scenario you had in mind where data would be accidentally written to prod?

2024-10-03 10:52 UTC, sherwoodf commented
This morning i ran it assuming it would write locally (because that how it currently works) and would have submitted data somewhere were it not for the fact that i got some error (see above).

I get that in most cases we do want to send data to the api, but without a magic undo button it feels there should be an intentional flag to say 'please actually do this' when we may also want to run the (otherwise) exact same command for other reasons.

2024-10-03 11:02 UTC, liviuba commented
> This morning i ran it assuming it would write locally (because that how it currently works) and would have submitted data somewhere (i don't know where, i wasn't paying attention to this) were it not for the fact that i got some error (see above).
> 
> I get that in most cases we do want to send data to the api, but without a magic undo button it feels there should be an intentional flag to say 'please actually do this' when we may also want to run the (otherwise) exact same command for other reasons.

To me, [this](https://github.com/BioImage-Archive/bia-integrator/pull/214#issuecomment-2390956083) looks like a bug for a missing validation where the tools fails in an unexpected way if it's missing config items for what it's executed for

2024-10-03 11:10 UTC, liviuba requested changes
Few suggestions

* The `Optional[Thing | None]`
* The bug @sherwoodf found, a validation somewhere that picks up if the app is missing configs for the mode it's called for would be nice IMO
* (happy to merge without, but mentioning in the spirit of tests being complete / green ticks meaning functional) Is it feasible to make the tests cover the code path where the api is involved?

2024-10-03 11:13 UTC, kbab commented on bia-ingest/bia_ingest/conversion/image_annotation_dataset.py
> +    persister: Optional[PersistenceStrategy | None] = None,
| is from 3.10+. Since we are requiring this in pyproject.toml I will make the change across the board. Thanks

2024-10-03 11:19 UTC, liviuba commented on bia-ingest/bia_ingest/conversion/image_annotation_dataset.py
> +    persister: Optional[PersistenceStrategy | None] = None,
Just to clarify, I meant that `Optional[PersistenceStrategy | None] == PersistenceStrategy | None | None` (IIRC), so the `| None` in the brackets is redundant, this wasn't about `|` itself

2024-10-03 18:25 UTC, kbab commented
> > > Should the default be on disk? I'm a bit worried about the default making changing to production data...
> > 
> > 
> > I am happy to change this. My impression was that the most common use would be for the API, but I guess users may want to explore things locally before running against the API. @liviuba do you have a preference for the default?
> 
> No strong preference aside from really wanting 'Undo' functionality in the api :) @sherwoodf what's the scenario you had in mind where data would be accidentally written to prod?

I have changed default to disk.

2024-10-03 18:26 UTC, kbab commented
> Minor comment, but i think it would be better if the 'written' log lines were debug level - these can always be viewed with a -v, and would reduce the quantity of output when dealing with long file lists. We might want to revisit some of the debug logs as well. 

Changed the `INFO` to `DEBUG`.

2024-10-03 20:17 UTC, kbab commented on bia-ingest/test/test_bia_ingest_cli.py
> +    result = runner.invoke(
Yes, it would be ideal to test - I have created [this clickup ticket](https://app.clickup.com/t/8696229nr). I will discuss implementation with you. The issue I have is that if I want to test with api locally, I would want a *clean* instance of the local api each time the test is run. But I also use my local api for dev purposes. I will explore getting pytest to spin up its own api and mongo instance.

2024-10-03 20:43 UTC, kbab commented
> > This morning i ran it assuming it would write locally (because that how it currently works) and would have submitted data somewhere (i don't know where, i wasn't paying attention to this) were it not for the fact that i got some error (see above).
> > I get that in most cases we do want to send data to the api, but without a magic undo button it feels there should be an intentional flag to say 'please actually do this' when we may also want to run the (otherwise) exact same command for other reasons.
> 
> To me, [this](https://github.com/BioImage-Archive/bia-integrator/pull/214#issuecomment-2390956083) looks like a bug for a missing validation where the tools fails in an unexpected way if it's missing config items for what it's executed for
> 
> LE: Happy for the default to be anything, but it would fail in the same way if it had a `--save-to-api` flag but no config set

Added assertions in __init__ methods to check valid parameters are supplied.

2024-10-04 08:25 UTC, liviuba approved these changes
LGTM!

2024-10-04 08:25 UTC, liviuba commented on bia-ingest/bia_ingest/persistence_strategy.py
> +        ), f"ApiPersister cannot be created. Expected valid instance of <class 'PrivateApi'>. Got : {type(api_client)} - are your API credentials valid and/or is the API server online?"
+1 "how to start fixing the error" in the error always useful!

2024-10-04 08:26 UTC, merged