Api pagination
BioImage-Archive/bia-integrator pull request #219
Opened 2024-10-08 14:48 UTC by liviuba

https://app.clickup.com/t/8695j4dpq

2024-10-08 16:35 UTC, sherwoodf requested changes
Having issues testing locally due to having wiped my workspace after the filename issues. I'm also getting pylance issues with two types that are passed in as variables - will try to figure this out tomorrow, but neither of those have anything to do with your changes here.

2024-10-08 16:35 UTC, sherwoodf commented on api/api/models/api.py
> +    start_uuid: Optional[UUID] = None
suggest renaming to 'start_from_uuid'

2024-10-09 10:21 UTC, sherwoodf commented
Currently getting 2 failing tests locally:
- test_get_studies
- test_search_image_multiple_results
But these are also failing on main...

2024-10-09 16:59 UTC, liviuba commented on api/api/tests/test_pagination.py
> +        params={"page_size": 3, "start_uuid": first_page[-1]["uuid"]},
Not sure I understand the suggestion, in general page_size sets the maximum size of the response, the client doesn't need to know ahead of time if they would get `page_size` results or less.

[This](https://github.com/BioImage-Archive/bia-integrator/pull/219/files#diff-1a8bbf7b53e35f14f2959bfd88c7e3dc603b9b8f1dac086ad2129b92ac59d881R43) covers cases where the client has a page size larger than the whole result set, and [this](https://github.com/BioImage-Archive/bia-integrator/pull/219/files#diff-1a8bbf7b53e35f14f2959bfd88c7e3dc603b9b8f1dac086ad2129b92ac59d881R94) covers the typical case where the client gets multiple pages (not knowing the total), until a page is smaller than page_size.

Happy to add the extra tests, but I don't know which scenario isn't covered

2024-10-10 08:33 UTC, sherwoodf approved these changes
LGTM

2024-10-10 09:12 UTC, merged