Add single settings class for api settings
BioImage-Archive/bia-integrator pull request #223
Opened 2024-10-16 14:53 UTC by liviuba

https://app.clickup.com/t/8695q6qjd

Most changes were workarounds to cyclical imports from the get_db dependency being moved to app.py

2024-10-18 11:25 UTC, kbab commented on api/api/auth.py
>  JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
Should this be using settings?

2024-10-18 11:26 UTC, kbab commented on api/api/auth.py
>  import os
Is this needed anymore?

2024-10-18 11:33 UTC, kbab requested changes
I left some comments on auth.py. Also in conftest.py:98 need to use settings and do not need `import os`.

A suggestion - which is not a requirement for approval is to make the initialisation on line 18 of `settings.py` absolute (e.g. `env_path = Path(__file__).parent / ".env" ` which will also simplify use of package. E.g. for testing I would not need to be in `api/api`. Happy to discuss after lunch.

Finally, not sure if it is my local config, but two tests for auth failed:
```
=========================== short test summary info ============================
FAILED tests/test_auth.py::test_create_user - assert 500 == 200
FAILED tests/test_auth.py::test_create_user_bad_token - AssertionError: ['Traceback (most recent call last):
=================== 2 failed, 36 passed, 1 warning in 10.44s ===================
```

2024-10-18 13:27 UTC, liviuba commented on api/api/auth.py
>  JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
yes! Missed it

2024-10-22 14:28 UTC, kbab requested changes
LGTM - just one change request and one comment

1. Change: api/api/tests/conftest.py:101 tries to access env variable.
2. I was wondering why asserts are used in the fixtures in conftest - should these be tests in their own right?

2024-10-22 14:36 UTC, liviuba commented
Fixed 1., missed it!

For 2, the asserts are there just to make sure nothing went wrong. They're not meant to be tests, just to build dependencies for tests, but it's nice to check the response for things.

2024-10-22 14:39 UTC, kbab approved these changes
LGTM!

2024-10-22 14:39 UTC, merged